### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by cturnbull** [samneirinck/posh-docker#19] opened 2017-06-07 08:30 UTC
```
PS C:\WINDOWS\system32> Install-Module -Scope CurrentUser posh-docker

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet provider must be available in 'C:\Program Files (x86)\PackageManagement\ProviderAssemblies' or
'C:\Users\Christopher\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet
provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

PS C:\WINDOWS\system32> Import-Module posh-docker
Import-Module : The specified module 'posh-docker' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module posh-docker
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-docker:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

Firstly, I'm a powershell virgin, though I like to think I can follow simple instructions. Please tell me what I'm doing wrong here? This is on Windows 10. I used admin PS.

**Comment by cturnbull** [comment] 2017-06-07 08:31
FWIW, Get-Module posh-docker returns nothing.

**Comment by samneirinck** [comment] 2017-06-07 17:47
I'm booting up a clean VM to see if I can reproduce this, I'll let you know what I find out.

**Comment by samneirinck** [comment] 2017-06-07 18:50
Does the following directory exist?
C:\Users\<username>\Documents\WindowsPowerShell\Modules\posh-docker

**Comment by cturnbull** [comment] 2017-06-08 10:54
Yes, this directory exists. It contains 0.7.1, which in turn contains the .psd1 and .psm1 files, and PSGetModuleInfo.xml

**Comment by samneirinck** [comment] 2017-06-12 17:30
What does `Get-ExecutionPolicy` return for you?

**Comment by samneirinck** [comment] 2017-08-23 18:52
I'll close this issue since it's been idle for quite a while. If you still have this problem, feel free to let me know and I'll open it again.

**Closed as completed by samneirinck** 2017-08-23 18:52 UTC
