### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by felixfbecker** [samneirinck/posh-docker#13] opened 2016-12-20 17:51 UTC
Running
```powershell
Install-Module -Scope CurrentUser posh-docker
```
yields
```
Install-Module : Parameter named "Scope" not found.
In Zeile:1 Zeichen:16
+ Install-Module -Scope CurrentUser posh-docker
+                ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module
```

Running
```powershell
Install-Module posh-docker
```
yields
```
Module posh-docker was not found in central repository
In C:\Users\felix\OneDrive\Dokumente\WindowsPowerShell\Modules\PsGet\PsGet.psm1:692 Zeichen:13
+             throw "Module $Module was not found in central repository ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Module posh-doc...tral repository:String) [], RuntimeException
    + FullyQualifiedErrorId : Module posh-docker was not found in central repository
```
What am I missing?

**Comment by samneirinck** [comment] 2016-12-21 11:06
Which operating system are you on? 
Could you execute `Get-Command Install-Module` and post its output?

**Comment by felixfbecker** [comment] 2016-12-21 11:11
Windows 10 Insiders Fast Ring 14986
```
$ get-command Install-Module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     0.0        PsGet
```

**Comment by samneirinck** [comment] 2016-12-21 11:15
It seems to me to be a conflict between the `PsGet` and `PowershellGet` modules. Do you actively use `PsGet`. 

I found the following link intereseting: https://til.secretgeek.net/powershell/psget_conflicts_with_PowerShellGet.html

**Comment by felixfbecker** [comment] 2016-12-21 11:19
This is an almost fresh machine, I don't use either

**Comment by samneirinck** [comment] 2016-12-21 11:25
This is the output I get from `Get-Command Install-Module`. The difference I see are the Source (&Version).
```CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     1.0.0.1    PowerShellGet
```
If you do a `Get-Module`, I believe you will see a `PsGet` entry in there. If you remove the `PsGet` folder in `C:\Users\felix\OneDrive\Dokumente\WindowsPowerShell\Modules\`, and start a new terminal session, I believe it should work.

**Comment by samneirinck** [comment] 2017-01-02 07:09
Did this solve your issue?

**Comment by opcon** [comment] 2017-01-02 08:12
I had the same issue, and removing the `PsGet` folder from the `Modules` fixed it for me

**Comment by samneirinck** [comment] 2017-01-03 06:52
I'm going to close this for now, since @opcon confirmed removing the `PsGet` folder fixed it for him/her. If it's still an issue, feel free to comment/re-open it.

**Closed as completed by samneirinck** 2017-01-03 06:52 UTC

**Comment by kitos9112** [comment] 2018-01-06 16:37
I had this issue too
Thanks for posting the instructions on how to fix it!

**Comment by w33zy** [comment] 2018-05-25 22:17
This fix still works.
